services:
  mysql:
    image: mysql:8.0
    container_name: easy-course-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Lalka123
      MYSQL_DATABASE: easy_course_db
      MYSQL_USER: easy_course_user
      MYSQL_PASSWORD: easy_course_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  easy-course-app:
    build: .
    container_name: easy-course-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: mysql-local
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/easy_course_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Lalka123
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data:
